project:
  type: website
  output-dir: docs

website:
  title: MIA TRENBEATH
  navbar:
    right:
      - href: about.qmd
        text: ABOUT
      - href: projects.qmd
        text: PROJECTS
      - href: writing.qmd
        text: WRITING
  page-footer:
    left: 2025 Mia Trenbeath
    
format:
  html:
    theme:
    - cosmo
    - styles.scss
    toc: true
    include-font-awesome: true
    page-layout: full



